### ISSUE TITLE
Previous count isn't working

### ISSUE THREAD

**Issue by KhanShaheb34** [ahmedsadman/covid19-bd#2]
Previous count showing the current count. Can you please fix that?

**Comment by ahmedsadman** [comment]
The basic working is:

1. During an update, if the count changes, then: `prev_count` will contain the current count and the current `count` will be updated to the new count.

2. If the count does not change in the last 24 hours, both `count` and `prev_count` will be equal. 

So as you can see, the `prev_count` is meant to keep a record of the last 24 hrs only so that API consumers can predict the change using `count - prev_count`. Sometimes if I make changes and deploy, counts will be overwritten and both `prev_count` and `count` would be the same, but it gets automatically fixed when pulling a fresh new report from IEDCR.

There might still be some bugs, but you get the basic idea of how it works.

**Comment by KhanShaheb34** [comment]
This is working now.  :blush:
