### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by KhanShaheb34** [ahmedsadman/covid19-bd#8]
I have a front end web app built using your API. But, today it was unable to load data. So, I checked your API and it is showing this:

![Screenshot from 2020-08-24 20-38-12](https://user-images.githubusercontent.com/35837768/91058253-10ad9080-e64a-11ea-967f-86298bbe5db8.png)

**Comment by ahmedsadman** [comment]
Hi, the website is down because I run out of Heroku free Dyno hours every month. I can't afford buying a server for this.

I will request all users to cache last response. This will help me save free minutes. Will post more details in README soon.

**Comment by KhanShaheb34** [comment]
Sure..

**Comment by ahmedsadman** [comment]
Notified in README of the new instruction for caching the last request. Closing this issue

**Comment by ahmedsadman** [comment]
To keep the project alive I would eventually need to buy a domain and migrate to a premium server plan.It's not possible for me to maintain server costs. So, I have added donation info. I would encourage everyone to contribute. Please let others know who use this service as well.

**Comment by KhanShaheb34** [comment]
@ahmedsadman I'm trying to run your API on my machine. But I'm confused what environment variables to set in the `.env` file.

**Comment by ahmedsadman** [comment]
@KhanShaheb34  It's `REPORT_URL` and it should point to the Google Sheets provided by IEDCR. Although, I don't think you will need to run your own instance because I have shifted my other apps in another account and the time-limit problem will appear in the last 4-5 days of each month.
_If you want to create a derivative from existing work, please abide by license and disclose the original source. TIA_

**Comment by KhanShaheb34** [comment]
Ok then. I thought maybe you're having trouble because of too many requests. So, I tried to host your API on another server. 😛

**Comment by ahmedsadman** [comment]
@KhanShaheb34  Not due to traffic but schedulers/CRON. Schedulers in Heroku force the Dyno to run 24 hours. So, I will always run out of minutes during the last week of each month, I have reduced to last 3-4 days by moving my other applications to a different place. 
If you want, of course, you can host it in your own server but that's not required at all, implementing some caching will be enough _(And I think it's a necessity too because your website fails to load if there are any API errors at all, this shouldn't be the case)_. If it's your own private server and NOT Heroku, then you have to change how the scheduling is handled.
